### ISSUE TITLE
Not loading on Ultra Sun

### ISSUE THREAD

**Issue by pokemonfan6498** [Jared0714/Multi-PokemonFramework#3]
I got latest release of Multi-Pokémon framework but it worked on all games except Ultra Sun, whatever I do the welcome text doesn't appear

**Comment by Jared0714** [comment]
@pokemonfan6498 latest version of both the plugin (v1.0.1) and game (1.2)? And have you gotten past the loading screens?

**Comment by pokemonfan6498** [comment]
In using game with official update 1.2

**Comment by pokemonfan6498** [comment]
And the screen flashes blue but no welcome text

**Comment by Jared0714** [comment]
You still haven't answered my question fully. I repeat, have you gotten past the loading screens and are you sure you're using the latest version of the plugin?

**Comment by Dustin1983** [comment]
I made an account to say that I'm having the same problem. Game version is 1.2, plugin version is 1.0.1 and I don't know if it matters but I'm playing on an old 3DS XL. Once I start the game I get the blue flash but after I load up my save there is no "Welcome" text and Select does nothing.

**Comment by Jared0714** [comment]
@Dustin1983 Ultra Sun, right? Could you see if the other games work? Also, would be best if we could take this over to the server as I am most active there.

**Comment by Jared0714** [comment]
I'm not entirely sure. It works completely fine on my end. Perhaps send me your save file. Also, let's continue this thread on Discord

**Comment by Ysejal** [comment]
Hello, I have the same issue

**Comment by FrostedGeulleisia** [comment]
was this ever figured out properly btw? all games work except USUM and the workaround mentioned in the above comment didn't do it either
