### ISSUE TITLE
Unidentified instruction crash 

### ISSUE THREAD

**Issue by pokemonfan6498** [Jared0714/Multi-PokemonFramework#6]
I now have issue with my Pokémon Omega Ruby and my other games whatever I try to enter a Trainer battle or battle with Wild Pokémon I always get same error.

**Comment by Jared0714** [comment]
An Arm11 crash, right? Just wait for the v1.0.3 update, it should come pretty soon. I've been working on it for the past month, and should come with many stability improvements, bug fixes, QoL changes and more.

**Comment by pokemonfan6498** [comment]
I have crash logs of those instances

сб, 23 июл. 2022 г., 18:18 Jared0714 ***@***.***>:

**Comment by pokemonfan6498** [comment]
Good because i want that this update fixed LayeredFS bug so i could use
randomised features

сб, 23 июл. 2022 г., 18:18 Jared0714 ***@***.***>:

**Comment by Jared0714** [comment]
Will not support ROM hacks, unfortunately.
